language: csharp
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number
install:
  - mono .nuget/nuget.exe restore BS.Output.VSO.sln -Verbosity detailed
script:
  - msbuild /p:Configuration=Release BS.Output.VSO.sln
before_deploy:
  - cd BS.Output.VSO
  - cd bin
  - cd Release
  - rm *.xml
  - rm *.pdb
  - zip -r BS.Output.VSO.zip *
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: 'BS.Output.VSO.zip'
  skip_cleanup: true
  on:
    all_branches: true
    tags: true